---
- name: Instala pacotes via amazon linux extras
  shell: "amazon-linux-extras install -y {{ item }}"
  become: yes
  with_items:
    - php7.2
    - python3.8
        
- name: Instala pacotes de dependencia
  yum:
    name: "{{ item }}"
    state: latest
  become: yes 
  with_items: 
    - httpd 
    - php-gd
    - php-mcrypt

- name: Download wordpress 
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: 'Descompactando o pacote wordpress'
  unarchive: 
    src: "/tmp/wordpress.tar.gz" 
    dest: "/var/www/"
    remote_src: yes 
  become: yes

- name: Copiando arquivo de config 
  copy: 
    src: "{{ wordpress_path_install }}/wp-config-sample.php"     
    dest: "{{ wordpress_path_install }}/wp-config.php" 
    remote_src: yes      
  become: yes 

- name: Configura database no arquivo wp-config 
  replace: 
    path: "{{ wordpress_path_install }}/wp-config.php" 
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - {regex: 'database_name_here', value: "{{ wordpress_db_name }}" }  
    - {regex: 'username_here', value: "{{ db_username }}" }  
    - {regex: 'password_here', value: "{{ db_password }}"}  
    - {regex: 'localhost', value: "{{ db_host }}"}
  become: yes  

- name: Movendo diretorio wordpress
  copy:
    src: "{{ wordpress_path_install }}/"
    dest: /var/www/html/
    remote_src: yes      
  become: yes  