---
- name: Instala pacotes via amazon linux extras
  shell: "amazon-linux-extras install -y {{ item }}" 
  become: yes
  with_items:
    - lamp-mariadb10.2-php7.2
    - python3.8

- name: Instala depedencias DB
  yum:
    name: "{{ item }}"
    state: present
  become: yes   
  with_items:  
    - mariadb-server     
    - MySQL-python

- name: Inicia servico DB 
  shell: "systemctl start mariadb"
  become: yes
    
- name: Cria Banco MySql
  mysql_db: 
    name: "{{ wordpress_db_name }}"
    login_user: root
    state: present
    
- name: 'Cria o usuário do MySQL'
  mysql_user:
    login_user: root
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - "{{ wordpress_host }}"

- name: Liberando conexao remota
  copy: 
    src: 'files/my.cnf'
    dest: '/etc/my.cnf'
    force: yes 
  become: yes  
  notify:
    restart MariaDB